public import StructuredQueriesCore

#if CasePaths
  import CasePaths
#endif

/// Defines and implements a conformance to the ``/StructuredQueriesCore/Table`` protocol.
///
/// - Parameters
///   - name: The table's name. Defaults to a lower-camel-case pluralization of the type,
///     _e.g._ `RemindersList` becomes `"remindersLists"`.
///   - schemaName: The table's schema name.
#if CasePaths
  @attached(
    extension,
    conformances: Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    CasePathable,
    CasePathIterable,
    names: named(init(_:)),
    named(init(decoder:))
  )
  @attached(
    member,
    conformances: Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(CodingKeys),
    named(Draft),
    named(From),
    named(QueryValue),
    named(Selection),
    named(TableColumns),
    named(_columnWidth),
    named(columns),
    named(schemaName),
    named(tableName),
    named(AllCasePaths),
    named(allCasePaths),
    named(_$Element)
  )
#else
  @attached(
    extension,
    conformances: Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(init(_:)),
    named(init(decoder:))
  )
  @attached(
    member,
    conformances: Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(CodingKeys),
    named(Draft),
    named(From),
    named(QueryValue),
    named(Selection),
    named(TableColumns),
    named(_columnWidth),
    named(columns),
    named(schemaName),
    named(tableName)
  )
#endif
@attached(memberAttribute)
public macro Table(
  _ name: String = "",
  schema schemaName: String = ""
) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "TableMacro"
  )

/// Defines a "selection" of columns that can be decoded from a query.
///
/// When selecting tables and fields from a query, this data is bundled up into a tuple:
///
/// ```swift
/// RemindersList
///   .group(by: \.id)
///   .join(Reminder.all) { $0.id == $1.remindersListID }
///   .select { ($0, $1.count()) }
/// // [(RemindersList, Int)]
/// ```
///
/// The `@Selection` macro allows you to bundle this data up into a dedicated type, instead:
///
/// ```swift
/// @Selection
/// struct ListWithCount {
///   let list: RemindersList
///   let count: Int
/// }
///
/// RemindersList
///   .group(by: \.id)
///   .join(Reminder.all) { $0.id == $1.remindersListID }
///   .select { ListWithCount.Columns(list: $0, count: $1.count()) }
/// // [ListWithCount]
/// ```
///
/// > Tip: `@Selection`s can also be used to build up common table expressions.
///
/// - Parameter name: The selection's name, _i.e._ for a common table expression. Defaults to a
///   lower-camel-case pluralization of the type, _e.g._ `RemindersList` becomes `"remindersLists"`.
#if CasePaths
  @attached(
    extension,
    conformances: _Selection,
    Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    CasePathable,
    CasePathIterable,
    names: named(init(_:)),
    named(init(decoder:))
  )
  @attached(
    member,
    conformances: _Selection,
    Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(CodingKeys),
    named(Draft),
    named(From),
    named(QueryValue),
    named(Selection),
    named(TableColumns),
    named(_columnWidth),
    named(columns),
    named(schemaName),
    named(tableName),
    named(AllCasePaths),
    named(allCasePaths),
    named(_$Element)
  )
#else
  @attached(
    extension,
    conformances: _Selection,
    Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(init(_:)),
    named(init(decoder:))
  )
  @attached(
    member,
    conformances: _Selection,
    Table,
    PartialSelectStatement,
    PrimaryKeyedTable,
    names: named(CodingKeys),
    named(Draft),
    named(From),
    named(QueryValue),
    named(Selection),
    named(TableColumns),
    named(_columnWidth),
    named(columns),
    named(schemaName),
    named(tableName)
  )
#endif
@attached(memberAttribute)
public macro Selection(
  _ name: String = ""
) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "TableMacro"
  )

/// Customizes a column generated by the ``/StructuredQueriesCore/Table`` protocol.
///
/// When the property's type is itself a table (_e.g._, a `@Table` or `@Selection` type), the
/// property represents a _group_ of columns instead of a single column. Column groups have no
/// single name and cannot be generated, but `primaryKey: true` can be used to specify a composite
/// primary key.
///
/// - Parameters:
///   - name: The column's name. Defaults to the property's name, _e.g._ 'id' becomes `"id"`.
///   - representableType: A type that represents the property type in a query expression. For types
///     that don't have a single representation in SQL, like `Date` and `UUID`.
///   - generated: Allows to declare the column as a read-only database computed column, making it
///     available for queries but not for updates.
///   - primaryKey: The column is its table's primary key.
///   - lazyInitializable: Optionalize this column in the generated `Draft` type so it can be
///     initialized later (by you, or by the database on insert).
@attached(peer)
public macro Column(
  _ name: String = "",
  as representableType: (any QueryRepresentable.Type)? = nil,
  generated: GeneratedColumnStorage? = nil,
  primaryKey: Bool = false,
  lazyInitializable: Bool? = nil
) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "ColumnMacro"
  )

/// Customizes a group of columns generated by the ``/StructuredQueriesCore/Table`` protocol.
///
/// - Parameters:
///   - primaryKey: These columns are the table's composite primary key.
///   - lazyInitializable: Optionalize this column group in the generated `Draft` type so it can be
///     initialized later (by you, or by the database on insert).
@available(*, deprecated, renamed: "Column")
@attached(peer)
public macro Columns(
  as representableType: (any QueryRepresentable.Type)? = nil,
  primaryKey: Bool = false,
  lazyInitializable: Bool? = nil
) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "ColumnsMacro"
  )

/// Tells StructuredQueries not to consider the annotated property a column of the table.
///
/// Like SwiftData's `@Transient` macro, but for SQL.
@attached(peer)
public macro Ephemeral() =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "EphemeralMacro"
  )

/// Explicitly bind a value to a query.
///
/// This macro explicitly binds a Swift value to a query. This is required when binding a value with
/// a query representations, like `JSONRepresentable`:
///
/// ```swift
/// Reminder.update { $0.notes = #bind(["Buy a new jacket"]) }
/// ```
///
/// > Tip: Explicit binding can also improve the performance of the Swift compiler when
/// > type-checking complex query expressions involving heavily overloaded operators and literals.
@freestanding(expression)
public macro bind<QueryValue: QueryBindable>(
  _ queryValue: QueryValue.QueryOutput,
  as queryValueType: QueryValue.Type = QueryValue.self
) -> BindQueryExpression<QueryValue> =
  #externalMacro(module: "StructuredQueriesMacros", type: "BindMacro")

/// Introduces a safe SQL fragment to a query.
///
/// The `#sql` macro also performs rudimentary parsing to detect invalid and partial query
/// fragments, _e.g._ unmatched parentheses and quotations. To opt out of this validation, use
/// `SQLQueryExpression.init(_:)`, instead.
///
/// > Tip: Selectively introducing SQL strings can also improve the performance of the Swift
/// > compiler when type-checking complex query expressions involving heavily overloaded operators
/// > and literals.
@freestanding(expression)
public macro sql<QueryValue>(
  _ queryFragment: QueryFragment,
  as queryValueType: QueryValue.Type = QueryValue.self
) -> SQLQueryExpression<QueryValue> =
  #externalMacro(module: "StructuredQueriesMacros", type: "SQLMacro")

@freestanding(expression)
public macro sql(
  _ queryFragment: QueryFragment,
  as queryValueType: Any.Type = Any.self
) -> SQLQueryExpression<Any> =
  #externalMacro(module: "StructuredQueriesMacros", type: "SQLMacro")

@attached(accessor, names: named(get))
public macro _PrimaryKeyDefault() =
  #externalMacro(module: "StructuredQueriesMacros", type: "PrimaryKeyDefaultMacro")

@attached(
  member,
  names: named(From),
  named(QueryValue),
  named(Selection),
  named(TableColumns),
  named(_columnWidth),
  named(columns)
)
@attached(
  extension,
  conformances: TableDraft,
  PartialSelectStatement,
  names: named(init(_:)),
  named(init(decoder:))
)
public macro _Draft<T>(_ primaryTable: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "TableMacro")

@attached(peer)
public macro _ColumnCheck<T>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckFailMacro")

@attached(peer)
public macro _ColumnCheck<T: Codable>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckFailJSONMacro")

@attached(peer)
public macro _ColumnCheck<T: QueryBindable>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckPassMacro")

@attached(peer)
public macro _ColumnCheck<T: QueryBindable & Codable>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckPassMacro")

@attached(peer)
public macro _ColumnCheck<T: Table>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckGroupMacro")

@attached(peer)
public macro _ColumnCheck<T: Table & Codable>(_ type: T.Type) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckGroupMacro")

@attached(peer)
public macro _ColumnCheck<T>(_ value: T) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckFailMacro")

@attached(peer)
public macro _ColumnCheck<T: QueryBindable>(_ value: T) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckPassMacro")

@attached(peer)
public macro _ColumnCheck<T: Table>(_ value: T) =
  #externalMacro(module: "StructuredQueriesMacros", type: "ColumnCheckGroupMacro")
